# Generated by Django 3.1.7 on 2021-04-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='image',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
